Add books feature
Willian-Berrocal/Awesome-books-project pull request #1
Opened 2022-10-24 22:49 UTC by emmanuellmhango

Added simple styling for easy access to the form

2022-10-24 23:08 UTC, addod19 commented
### Hi @emmanuellmhango and @Willian-Berrocal, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is failing linter checks

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-25 01:09 UTC, Gopxfs requested changes
# ♻️ STATUS: REQUIRED CHANGES ♻️

## Hi @emmanuellmhango @Willian-Berrocal 👋,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/l4JzhjVCQiWgeAOFa/giphy.gif">

## Highlights :rocket:
✔️ Add book function working perfectly.
✔️ LocalStorage being updated as expected. Well done!
✔️ No linter errors.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🗒️  
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-25 01:09 UTC, Gopxfs commented on main.js
> +  localStorage.setItem('libraryData', JSON.stringify(library));
As requested in the project requirements: 
![image](https://user-images.githubusercontent.com/42799579/197651484-06ba0e1a-4d27-4369-aaa3-39ee8ce2139f.png)

Your project currently can add books properly, remove them and update the localStorage! Very well done job 😄. So, what is the problem? Please note that your removeBook function uses the 'title' of your books to filter them. This is causing some side effects to your code, like removing all the books with the same title: 

Your booklist:
![image](https://user-images.githubusercontent.com/42799579/197657987-3a2e744d-3e4a-468e-8e6e-5df4b119de41.png)

Same booklist after removing only the last element:
![image](https://user-images.githubusercontent.com/42799579/197658035-d8f8b34f-f0f4-4d84-917b-9f558248650c.png)

After refreshing the page:
![image](https://user-images.githubusercontent.com/42799579/197658062-e80b0b56-d5e3-4f4e-b646-aaedb8bbe2c4.png)

> My tip for you: You can add ids to identify each of your books and filter them by id instead of title. By doing this, you will avoid removing the wrong element 😉. Good luck and keep up the good work!

2022-10-25 02:38 UTC, Gopxfs commented
# 🟢 STATUS: APPROVED 🟢

## Hello @emmanuellmhango 👋,

Your project is complete! You followed all the requirements, feel free to merge it! 😄
Congratulations! 🎉 

<img src="https://media.giphy.com/media/cXblnKXr2BQOaYnTni/giphy.gif">

## Highlights
✔️ Linters are passing successfully.
✔️ Implemented all the changes requested by the previous reviewer. Well done!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-25 02:38 UTC, Gopxfs approved these changes
# 🟢 STATUS: APPROVED 🟢

## Hello @emmanuellmhango 👋,

Your project is complete! You followed all the requirements, feel free to merge it! 😄
Congratulations! 🎉 

<img src="https://media.giphy.com/media/cXblnKXr2BQOaYnTni/giphy.gif">

## Highlights
✔️ Linters are passing successfully.
✔️ Implemented all the changes requested by the previous reviewer. Well done!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-25 02:41 UTC, merged